on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Get quick assessment by report
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: get Microsoft 365 quick assessments
      uses: ./ # Uses an action in the root directory
      with:
        report-name: ${{ secrets.REPORT_NAME }}