on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Get quick assessment by deployment bicep
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy with bicep
      id: deploybicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUP}}
        template: ./deploy/Storage.bicep
        parameters: storageAccountType=Standard_LRS
    - run: echo ${{ steps.deploybicep.outputs.deploymentId }}

    - name: get Microsoft 365 quick assessments
      uses: ./ # Uses an action in the root directory
      with:
        deployment-id: ${{ steps.deployarm.outputs.deploymentId }}